#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxdg-basedir
Version  : 1.2.0
Release  : 1
URL      : https://github.com/devnev/libxdg-basedir/archive/libxdg-basedir-1.2.0.zip
Source0  : https://github.com/devnev/libxdg-basedir/archive/libxdg-basedir-1.2.0.zip
Summary  : An implementation of the XDG Base Directory specification
Group    : Development/Tools
License  : MIT
Requires: libxdg-basedir-lib = %{version}-%{release}
Requires: libxdg-basedir-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : graphviz

%description
No detailed description available

%package dev
Summary: dev components for the libxdg-basedir package.
Group: Development
Requires: libxdg-basedir-lib = %{version}-%{release}
Provides: libxdg-basedir-devel = %{version}-%{release}

%description dev
dev components for the libxdg-basedir package.


%package lib
Summary: lib components for the libxdg-basedir package.
Group: Libraries
Requires: libxdg-basedir-license = %{version}-%{release}

%description lib
lib components for the libxdg-basedir package.


%package license
Summary: license components for the libxdg-basedir package.
Group: Default

%description license
license components for the libxdg-basedir package.


%prep
%setup -q -n libxdg-basedir-libxdg-basedir-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540942843
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1540942843
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxdg-basedir
cp COPYING %{buildroot}/usr/share/package-licenses/libxdg-basedir/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libxdg-basedir.so
/usr/lib64/pkgconfig/libxdg-basedir.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxdg-basedir.so.1
/usr/lib64/libxdg-basedir.so.1.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxdg-basedir/COPYING
