#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxdg-basedir
Version  : 1.2.3
Release  : 4
URL      : https://github.com/devnev/libxdg-basedir/archive/libxdg-basedir-1.2.3/libxdg-basedir-1.2.3.tar.gz
Source0  : https://github.com/devnev/libxdg-basedir/archive/libxdg-basedir-1.2.3/libxdg-basedir-1.2.3.tar.gz
Summary  : An implementation of the XDG Base Directory specification
Group    : Development/Tools
License  : MIT
Requires: libxdg-basedir-lib = %{version}-%{release}
Requires: libxdg-basedir-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : perl

%description
# libxdg-basedir
This is my fork of **libxdg-basedir**, by Mark Nevill. The original appears to be unmaintained.

%package dev
Summary: dev components for the libxdg-basedir package.
Group: Development
Requires: libxdg-basedir-lib = %{version}-%{release}
Provides: libxdg-basedir-devel = %{version}-%{release}
Requires: libxdg-basedir = %{version}-%{release}

%description dev
dev components for the libxdg-basedir package.


%package lib
Summary: lib components for the libxdg-basedir package.
Group: Libraries
Requires: libxdg-basedir-license = %{version}-%{release}

%description lib
lib components for the libxdg-basedir package.


%package license
Summary: license components for the libxdg-basedir package.
Group: Default

%description license
license components for the libxdg-basedir package.


%prep
%setup -q -n libxdg-basedir-libxdg-basedir-1.2.3
cd %{_builddir}/libxdg-basedir-libxdg-basedir-1.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618957958
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1618957958
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libxdg-basedir
cp %{_builddir}/libxdg-basedir-libxdg-basedir-1.2.3/COPYING %{buildroot}/usr/share/package-licenses/libxdg-basedir/7b09743cfe3dca39cdc24ac6729753ac15662176
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/basedir.h
/usr/include/basedir_fs.h
/usr/lib64/libxdg-basedir.so
/usr/lib64/pkgconfig/libxdg-basedir.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxdg-basedir.so.1
/usr/lib64/libxdg-basedir.so.1.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxdg-basedir/7b09743cfe3dca39cdc24ac6729753ac15662176
